language: java
jdk:
- oraclejdk8
env:
  global:
    secure: XEN1E9bA6az2Tkj0ihMZPxQVwGwxKs20YVEn+fuq2WASsM5CWXoNc3D8YABZ3j7om6/EG0OeFzZeytHXDte0g3iAxa8/2hplp0JqCRozya4sMLd7UWohPXUrC23+MI5ZUjy3+jPinChTSLqGNMKfcE5CqnuQqtKrDgc2w1tqlk4C3rScx2YhuVV1CQjqIA4bRPEHXqkS1Xl1Ul/D2nJfXtWcZFl1taehfM5g5WmFebJJZmn6hLCa43xgMhwYsjEPjMHMDeHqPpAJSVspY+HrHLuCiAK9z6GTgGU3sEcYNcJs9zsgHavKYUeLjR2LMrK7wlS7hYC4VmQlCYBPnBIbivpzGpXNZgNZ9zgSIP2ZVYmDW8rOWzxmTYkNQI2aug9ky9xV5NE+4rSflQoA+VMFGNvMHT5uwO58yaK/D6vW2Y5k1kqjucfVWQzV9u02+24WsP4XCiSmwRc/47HI3hiH6Bp4yGNm4x81GyQ+ea/54DClMXklX0tG8RPKL0odJ+IXK070+7WOnMHmg8hYVS9htjZLEN4dKXnbxIAd4PJCOTlXkpLUUGh0nD3Mn4x0rNmNRMVIdaNIs3oNlNnKQbWVRr6AZDk2B8Y4TsgizvdldGUTAkdX+F+S8cJFnjV2+n0CApzW2cV0Q/oDPwFsjKJLI+6TuPUOhpr1Qqt7IEImJyM=
