language: java
install: ''
script:
- export TERM=dumb
- ./gradlew wrapper
- ./gradlew clean alp42 publish --stacktrace
jdk:
- oraclejdk8
env:
  global:
    secure: E1HKFlmDQix545ydOGHlTIEb6bcDTFdXhtmuFfWDUJHkrROZR0Zgf+6kS2qH+Z65JbOVlm2sAn5bV+BUogbJGQI4wB1N+odFCOmZomHIDf9YASDaimjTCJVklsegyuvLupppAhHrWkFwZ7ulU4IWkU2jurWk3qCTFeGhFbx27k0joV6cKpft9xu5yh6bgHGOzt2dvJiQJmE4+JQjgI464RO50EjCN1rOepgnUh0Kb1Ldn9BwAaKBcuLODgbtupo932EFVKtddid9pwMNkLenBtuLsMvE1lChIDGQG1CTrX5GdHBlAhA6K0Svwo4MxnaE6ArXwF63y/lJqkOQZOeqjUhskkNdGrjd6Z2Sgch87vgT7gBKEQ9awD6dZPgMcLHNFR/x9akpKc6c6kQCGVpwGp4wZr8ACVV2leL0uLwalZGehKB+Z8vDcaOqAoQAoNK9Wx+o0HzHkmhMsbuUJ6wXQOns/AjlpP5oNcOYvfdbOgTyBLrZFJRY5jpRBoXxIuE7yNYdpP85nQuV6io6RFERrWFv7kYc7zV4POAdWRGZOFGgS6r9MYhmIMeMWJg1ayw6kjdYp7ovfzeSPp5A990YtZt8o6pHIeLhba4lB5U/oTWJYnggsX1Ldt94VlMhWpcz9oDGS8P5cODaZjjNrc76zPSAnsZba0ktxb2vKcIU/mU=
