:numbered:

[appendix]
== Pattern Templates

Patterns should be written in a more or less formal way.
A common structure makes it easier to compare patterns and find the best fitting one for a concrete problem.

At the moment alp42 uses two different pattern structures.
A simple and leightweight one based on the pattern approach by <<schuetz-pattern, Didi Schütz et.al.>>.
The other template follows the more exhaustive pattern structure used by Mary Lynn Manns and Lynda Rising for their <<manns-fearless,Fearless Change Patterns>>.

You can find ready-to-use tempaltes for both structures in our https://github.com/alp42/alp42/tree/master/src/main/resources/templates[GitHub Repository]

=== Simple Pattern Template

==== Context

Where does the problem appear?
Under which circumstances can the problem be seen?

==== Problem

Tell about the problem.
Why is it a complicated problem and difficult to solve?

Try to describe the problem as specific as possible.
Experience shows that this is a hard task, but it is essential for a high quality pattern.

==== Forces

Which forces have an effect to the problem or the solution?
How does the pattern balance these forces?

==== Solution

How does the pattern solve the problem?
Describe the pattern and how it should be used.

==== Consequences

What is the expected outcome of using the pattern?
Which positive and negative consequenes result from the pattern?

==== Variants

If there are different variants of the pattern used, give a short description of them here.

=== Exhaustive Pattern Template

==== Opening Story

==== Summary

==== Context

==== Problem

==== Forces

==== Essence of the Solution

==== More about the Solution

==== Resulting Context

==== Known Uses
